// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/multi-db-sqlboiler/adapter/configuration"
	"github.com/Pranc1ngPegasus/multi-db-sqlboiler/adapter/infrastructure"
	"github.com/Pranc1ngPegasus/multi-db-sqlboiler/adapter/logger"
)

// Injectors from inject.go:

func initialize() infrastructure.RDBConnector {
	config := configuration.Get()
	zerologLogger := logger.New()
	rdbConnector := infrastructure.NewRDBConnector(config, zerologLogger)
	return rdbConnector
}
